### ISSUE TITLE
Bug: bad argument #2 to 'form at' (number expected, got nil)

### ISSUE THREAD

**Issue by Shivansh-007** [pwntester/octo.nvim#145]
## Issue Description
Bug Report

### Describe what happened (or what feature you want)
On running `:Octo pr list` and selecting a PR.
```vim
Error executing
 vim.schedule lua callback: ...site/pack/packer/start/octo.nvim/highlights.lua:30: bad argument #2 to 'form at' (number expected, got nil)
```

I am using the same config, which was given in `README.md`, and ran `PackerInstall` and `PackerCompile` after setting it up

![Screenshot from 2021-05-16 07-01-19](https://user-images.githubusercontent.com/69356296/118382607-f91d9a00-b614-11eb-88ac-187f30f34c4c.png)

### Describe what you expected to happen
Supposed to open the PR description, this actually does happen but after the error was produced.

### How to reproduce it (as minimally and precisely as possible)

1. `:Octo pr list` and select any random PR
2. Open it

### Tell us your environment

It is a https://github.com/python-discord/bot environment

**Comment by pwntester** [comment]
Thanks for reporting the issue. Can you send me the output of `:hi Normal` in your system?

**Comment by Shivansh-007** [comment]
Here @pwntester 

![Screenshot from 2021-05-16 17-02-20](https://user-images.githubusercontent.com/69356296/118395527-80e0c400-b668-11eb-8248-b3a31aaf70db.png)

**Comment by pwntester** [comment]
Hi @Shivansh-007 it should be fixed now, let me know if it works for you

**Comment by Shivansh-007** [comment]
New bug 😬 

![Screenshot from 2021-05-16 19-17-34](https://user-images.githubusercontent.com/69356296/118399565-69f79d00-b67b-11eb-8a41-4d98bf4f8744.png)

**Comment by pwntester** [comment]
Unfortunately, that error is not very verbose. Is that everything that appears in `:messages`?

**Comment by Shivansh-007** [comment]
Umm, that doesn't seem to happen anymore, but the previous error is still not resolved and there is a new one :D 

![Screenshot from 2021-05-16 19-40-15](https://user-images.githubusercontent.com/69356296/118400297-a7115e80-b67e-11eb-8d78-61a4fd5fb6f7.png)

**Comment by pwntester** [comment]
Are you opening a PR in a public repo? If so, can you share the repo and PR number?

**Comment by Shivansh-007** [comment]
Nope, I doing it locally, give me a minute, I will upload it on my dotfiles.

**Comment by Shivansh-007** [comment]
Okay, pushed, https://github.com/Shivansh-007/dotfiles/tree/main/.config/nvim

**Comment by pwntester** [comment]
In the error, it seems like you were listing the issues or PRs of a repo. What was the full command you entered before getting the error?

**Comment by Shivansh-007** [comment]
`:Octo pr list` and clicking any random PR.

**Comment by pwntester** [comment]
Thanks, what is the repo you are currently listing the issues for? I need it to reproduce the issue

**Comment by Shivansh-007** [comment]
> Thanks, what is the repo you are currently listing the issues for? I need it to reproduce the issue

https://github.com/python-discord/bot/pull/1234

**Comment by pwntester** [comment]
Thanks, can you try again. It seems like the GH API was missing some data as the reviewer requested when its a team

**Comment by Shivansh-007** [comment]
Ah Alright, works perfectly! Thanks ❤️

**Comment by pwntester** [comment]
Cool, will keep an eye on the GraphQL API to see if/when GH fixes the issue
